### ISSUE TITLE
Crow kinda breaks threadding for me

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#188] opened 2021-08-05 19:58 UTC
Soo i have this
```cpp
#include "app.h"

#include <thread>

App::App()
{

    this->ctrl = new Controller;
    this->site = new Site(this->ctrl);
}

App::~App()
{
    delete this->site;
    delete this->ctrl;
}

void App::run()
{
    std::thread controllerThread(&Controller::run, this->ctrl);
    std::thread siteThread(&Site::run, this->site);

    siteThread.join();
    controllerThread.join();
}
```
```cpp
#include "site.h"
#include "json/json.hpp"


Site::Site(Controller* otherController)
{
    this->cntrl = otherController;
    nlohmann::json j = configFile.read();

    this->port = j["site"]["port"];
    this->password = j["site"]["password"];


    
    
    CROW_ROUTE(this->app, "/").methods(crow::HTTPMethod::GET)([this](){return this->loginPageGet();});
    CROW_ROUTE(this->app, "/").methods(crow::HTTPMethod::POST)([this](const crow::request& req)
                                                        {return this->loginPagePost(req);});
    CROW_ROUTE(this->app, "/settings").methods(crow::HTTPMethod::POST)([this](const crow::request& req)
                                                        {return this->settingsPage(req);});

}

void Site::run()
{
    app.port(this->port).run();
}

//Private

std::string Site::loginPageGet()
{
    CROW_LOG_INFO << "Serving login page";
    auto page = crow::mustache::load("login.html");
    return page.render();
}

std::string Site::loginPagePost(const crow::request& req)
{
    CROW_LOG_INFO << "Login post request";

    crow::multipart::message passwd(req);

    return passwd.parts[0].body == this->password ? this->dashboardGet() : "Wrong password";
}

std::string Site::dashboardGet()
{
    CROW_LOG_INFO << "Serving Dashboard page";

    crow::mustache::context ctx;

    ctx["threshold"]    = this->cntrl->getThreshold();
    ctx["temp"]         = this->cntrl->getTemp();
    ctx["range"]        = this->cntrl->getRange();
    ctx["state"]        = this->cntrl->getState() ? "On" : "Off";

    auto page = crow::mustache::load("dashboard.html");

    return page.render(ctx);
}
std::string Site::settingsPage(const crow::request& req)
{
    CROW_LOG_INFO << "Setting page call";

    crow::multipart::message msg(req);

    this->cntrl->setThreshold(std::stof(msg.parts[0].body));
    this->cntrl->setRange(std::stof(msg.parts[1].body));

    CROW_LOG_INFO << "New threshold: " << this->cntrl->getThreshold() << 
                    ". New range: " << this->cntrl->getRange();
    
    return this->dashboardGet();
}
```
and i've tried this with and without `multithreaded()` and with a thread to a dummy function instead of the site thread, and if i make a thread of `Site` i can't terminate the program via SIGTERM or SIGINT. What appears to happen is the site thread closes but the other thread remains i have to terminate it manually via SIGKILL. Am i missing something that is making this not work ?

**Comment by The-EDev** [comment] 2021-08-05 20:03
So your problem seems to be similar to #187. The problem is that Crow's signal handler is overriding what you have. The solution would be to call `app.signal_clear()` and create your own signal handler instead, just make sure it calls `app.stop()`.

Let me know if this doesn't work for you.

**Comment by Iuliean** [comment] 2021-08-05 20:07
I'm on it. i suppose `app.signal_clear()` should be called before `app.run()` =))

**Comment by The-EDev** [comment] 2021-08-05 20:09
> i suppose app.signal_clear() should be called before app.run() =))

Indeed :), all it does is disable Crow's signal handler.

**Comment by Iuliean** [comment] 2021-08-05 20:22
Ok i tested it and it works, though i did not make my own signal handler how bad is it if do not call `app.stop()` because if i have to write my own signal handle i think i have to refactor my code a bit since i am doing some threading myself

**Comment by The-EDev** [comment] 2021-08-05 20:27
What stop does is call the ASIO's `io_service`s' `stop()` method. I've never tried terminating Crow without doing that so I'm not sure what the effect is.. I'll close this issue since the original question has been answered. But please don't hesitate to ask for help if you need it.

**Closed** 2021-08-05 20:27 UTC
Labels: question

**Comment by Iuliean** [comment] 2021-08-05 20:29
Hmm i think i'll leave it without a signal handler for now, if something breaks i'll make one. Thanks again for the help

**Comment by The-EDev** [comment] 2021-08-05 20:30
No problem :)
