### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by geotinc** [CrowCpp/Crow#225] opened 2021-09-27 15:49 UTC
Hello, don't know if it's a real problem but the following code :

![image](https://user-images.githubusercontent.com/20421571/134941932-87647669-9bde-4596-8564-4f490d7a3ee6.png)

produce the following response in postman :
![image](https://user-images.githubusercontent.com/20421571/134941971-c9c1e685-8617-405d-8e73-38d24bc49540.png)

how to have the real key like "Test" and "accessToken" ?

Thanks for helping

**Comment by The-EDev** [comment] 2021-09-27 15:59
Like I said in the other issue, this has never happened, could you please provide more information? do the json examples work fine?

**Comment by geotinc** [comment] 2021-09-27 16:14
I try the example code :
![image](https://user-images.githubusercontent.com/20421571/134945982-85a3572d-b6ba-4390-b153-1e5d38ed955e.png)
And I have the same problem :
![image](https://user-images.githubusercontent.com/20421571/134946098-78ab7956-ab07-4d64-af9e-b187c5aeaa88.png)

**Comment by The-EDev** [comment] 2021-09-27 16:20
Used the exact same code as you, got this:
![image](https://user-images.githubusercontent.com/60552923/134947164-0e86bcbf-adea-4f95-bf23-3cb09a53af94.png)

Can you tell me what OS you're running, what compiler version, what Crow version, etc...

**Comment by geotinc** [comment] 2021-09-27 16:36
It seems that it is an UT8 error :
116 101 115 116 in hexadecimal is :
74 65 73 74 = "test"

![image](https://user-images.githubusercontent.com/20421571/134949304-8e983a97-f924-4eb5-84e0-dab114fb47ea.png)

My os is :
![image](https://user-images.githubusercontent.com/20421571/134949356-3bbf643a-9962-4de7-bad6-b74eb71a9566.png)

I build with Visual Studio 2019 :
![image](https://user-images.githubusercontent.com/20421571/134949443-26f32635-5aa0-4d44-bce0-9fcb6bd032e2.png)

and the crow version has been installed with vcpkg :
![image](https://user-images.githubusercontent.com/20421571/134949612-9ad5c74c-bbdf-40b5-9e5e-e1abc57f49f0.png)

Hope it help.

Thanks a lot.

**Comment by The-EDev** [comment] 2021-09-27 16:50
Can you check the URL in your browser instead of postman? This way we can tell whether it's postman or Crow that's giving the problem

**Comment by geotinc** [comment] 2021-09-27 17:54
Same in problem in chrome and firefox :
![image](https://user-images.githubusercontent.com/20421571/134960065-f7c4e172-025e-4c8d-a2e5-9290a5fbf2c5.png)

**Comment by The-EDev** [comment] 2021-09-27 17:55
hmmm, I'll look into why it's doing that

**Comment by geotinc** [comment] 2021-09-29 12:10
For information, if I return directly a string value without instanciate a 
![image](https://user-images.githubusercontent.com/20421571/135265444-b2ec6da2-726a-458e-ad06-8ebe2517d294.png)

It works, do you think other include in my project can alter the rendering of WVVALUE ?

![image](https://user-images.githubusercontent.com/20421571/135265717-f0e9a04f-060e-45da-8b10-2e3d4c5708bd.png)

**Comment by The-EDev** [comment] 2021-09-29 12:15
it is possible, I don't know what else you're including or what compile settings you have, also it might be best to use this format:
\`\`\`
Paste Code Here
\`\`\`
instead of using pictures.

**Comment by geotinc** [comment] 2021-09-29 13:09
We have found the problem in json.h file in method 
`inline void escape(const std::string& str, std::string& ret)`

We have replace :
`for(unsigned char c:str)`

by
`for(auto c:str)`

And it's work.

Any idea to fix the problem at project level without change libraries code ?

**Comment by The-EDev** [comment] 2021-09-29 13:27
This is weird.. The code currently in `json.h` is `for auto c:str`, did you mean change that to `for(unsigned char c:str)` or are you using an old version of Crow?

**Comment by The-EDev** [comment] 2021-09-30 00:41
Oh my god, I'm so so sorry. This issue is a duplicate of #195 and has been fixed on `master` in #196. I don't know how it slipped past me or why I didn't add it in a new hotfix to 0.3. I'm sorry again.

**Closed by The-EDev** 2021-09-30 00:41 UTC
Labels: bug, duplicate
