### ISSUE TITLE
Server cannot close WebSocket connection (segmentation fault)

### ISSUE THREAD

**Issue by ArthoPacini** [CrowCpp/crow#149] opened 2021-06-17 06:52 UTC
So I wrote a code that automatically closes all websockets connections 

```cpp
#define CROW_MAIN
#include "crow_all.hpp"
#include <unordered_set>
#include <mutex>

std::mutex mtx;;
std::unordered_set<crow::websocket::connection*> users;


void close_connections()
{
    while(true)
    {
        for(std::uint16_t i = 10; i != 0; --i)
        {
            std::this_thread::sleep_for(std::chrono::seconds(1));
            std::cout << "closing connections in " << i << " seconds..." << std::endl;   
        }
        
        std::cout << "closing " << users.size() << " connections now..." << std::endl;
        //mtx.lock();

        for(auto u : users)
            u->close();

        users.clear();

        //mtx.unlock();

    }
}

int main()
{
    crow::SimpleApp app;

    CROW_ROUTE(app, "/ws")
        .websocket()
        .onopen([&](crow::websocket::connection& conn){
                CROW_LOG_INFO << "new websocket connection";
                std::lock_guard<std::mutex> _(mtx);
                users.insert(&conn);
                })
        .onclose([&](crow::websocket::connection& conn, const std::string& reason){
                CROW_LOG_INFO << "websocket connection closed: " << reason;
                std::lock_guard<std::mutex> _(mtx);
                users.erase(&conn);
                })
        .onmessage([&](crow::websocket::connection& /*conn*/, const std::string& data, bool is_binary){
                std::lock_guard<std::mutex> _(mtx);
                for(auto u:users)
                    if (is_binary)
                        u->send_binary(data);
                    else
                        u->send_text(data);
                });

    CROW_ROUTE(app, "/")
    ([]{
        return "Hello World";
     });


    std::thread(close_connections).detach();

    app.port(40080)
        .multithreaded()
        .run();
}
```

So `close_connections()` will eventually loop all websocket connections and try to close them, if there's at least 1 websocket connection opened, it will crash

```console
(2021-06-17 06:32:02) [INFO    ] Crow/0.3 server is running at 0.0.0.0:40080 using 6 threads
(2021-06-17 06:32:02) [INFO    ] Call `app.loglevel(crow::LogLevel::Warning)` to hide Info level logs.
closing connections in 10 seconds...
closing connections in 9 seconds...
closing connections in 8 seconds...
closing connections in 7 seconds...
closing connections in 6 seconds...
closing connections in 5 seconds...
(2021-06-17 06:32:09) [INFO    ] new websocket connection
closing connections in 4 seconds...
closing connections in 3 seconds...
closing connections in 2 seconds...
closing connections in 1 seconds...
closing 1 connections now...
(2021-06-17 06:32:12) [INFO    ] websocket connection closed: quit
Segmentation fault (core dumped)
```

using g++-10 debbuger it shows that an exception has occurred at file `/usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp`

line 245:

![image](https://user-images.githubusercontent.com/22568556/122344290-03d19480-cf1d-11eb-993a-5104f90cdcc3.png)

What would be the correct way of closing a connection?

**Comment by The-EDev** [comment] 2021-06-17 11:44
If I'm reading this correctly, you have a separate thread just closing all websocket connections every 10 seconds...

AFAIK websockets are there to maintain a persistent connection where a client and a server can send and receive messages independent of HTTP's "request then response" framework.
Which means that your method kind of negates the purpose of using websockets in the first place.

regardless, your segfault might be caused by the fact that you're erasing your element on 2 separate threads, so there's a good chance the connection is being erased by the first `close()` and later referenced by the `.onclose` handler (`onclose` gets called regardless of who closes the connection), since you're trying to reference what had just become a null pointer.

**Comment by ArthoPacini** [comment] 2021-06-18 01:53
The `close_connections()` function is just a test, but it seems that the server cannot close a websocket connection, the exception is throw in boost::asio namespace..

```cpp
    #define CROW_MAIN
    #include "crow_all.hpp"
    #include <unordered_set>
    #include <mutex>
    
    std::mutex mtx;;
    std::unordered_set<crow::websocket::connection*> users;
    


int main()
{
    crow::SimpleApp app;

    CROW_ROUTE(app, "/ws")
        .websocket()
        .onopen([&](crow::websocket::connection& conn){
                CROW_LOG_INFO << "new websocket connection";
                std::lock_guard<std::mutex> _(mtx);
                users.insert(&conn);
                conn.close();
                })
        .onclose([&](crow::websocket::connection& conn, const std::string& reason){
                CROW_LOG_INFO << "websocket connection closed: " << reason;
                std::lock_guard<std::mutex> _(mtx);
                users.erase(&conn);
                })
        .onmessage([&](crow::websocket::connection& /*conn*/, const std::string& data, bool is_binary){
                std::lock_guard<std::mutex> _(mtx);
                    
                for(auto u:users)
                    if (is_binary)
                        u->send_binary(data);
                    else
                        u->send_text(data);
                });

    CROW_ROUTE(app, "/")
    ([]{
        return "Hello World";
        });


    app.port(40080)
        //.multithreaded()
        .run();
}
```

even this code throws an error. so if the client destroy the connection without sending a close signal to the server, the server will have invalid connections, this is not an error of Crow, but it the protocol of WebSockets, but if the server would ping the client and wait to see if it don't get a pong back and tries to close the connection, it will crash

**Comment by The-EDev** [comment] 2021-06-19 12:11
Well I just tested your last code, and it worked for me... Which version of boost are you using?

**Comment by The-EDev** [comment] 2021-06-28 16:32
I'll close this for now, @ArthoPacini Please reopen this if you would like to continue working on fixing the issue, or if anyone is having a similar issue.

**Closed by The-EDev** 2021-06-28 16:32 UTC
Labels: further information required
