### ISSUE TITLE
SIGPIPE

### ISSUE THREAD

**Issue by jessfraz** [CrowCpp/Crow#331] opened 2022-02-04 20:15 UTC
Seeing a failure writing back to the socket for a response:

```
system:32 - happened while sending buffers
An uncaught exception occurred: write: Broken pipe
```

coming from https://github.com/CrowCpp/Crow/blob/master/include/crow/http_connection.h#L690

It doesn't happen every time, but seems to happen on long responses? So could it be a timeout, or maybe the response size is too large although that seems odd

we have the timeout for crow set to `88` and the response is definitely not taking longer than that, but the socket to write back out is closing prematurely

**Comment by The-EDev** [comment] 2022-02-04 21:27
Hi @jessfraz, I'm almost 100% sure I fixed this issue while working on #306 (the issue isn't related, but it made the issue obvious). The only thing left is making a PR for the fix.

The root cause of the issue is that when sending static files or responses larger than 1MB if the connection is set to close (though using HTTP/1.0 or `connection: close`) the socket is closed immediately after the first response chunk is sent. Until the PR is made and merged the best course of action is to increase the stream threshold so that large responses don't get streamed(using [stream_threshold](https://crowcpp.org/reference/classcrow_1_1_crow.html#ae92390d22f6fc99987c41a617be71d64))

**Comment by jessfraz** [comment] 2022-02-04 21:43
omg thanks! I was knee deep in strace :) will keep an eye out for the fix

**Comment by jessfraz** [comment] 2022-02-05 02:41
as another note, can you all set up GitHub sponsors? I see you have opencollective but its a lot easier to send money through GitHub's built in thing.

**Comment by The-EDev** [comment] 2022-02-05 02:50
Thanks a lot for your interest in supporting Crow financially. We already have a [GitHub Sponsors Page](https://github.com/sponsors/CrowCpp) set up. I hope nothing is broken with that

**Comment by jessfraz** [comment] 2022-02-05 02:51
Oh nice sorry! For some reason when I clicked the thing at the bottom of the issue I only saw open collective, but thank you! Doing this now!

**Closed** 2022-02-15 14:10 UTC
Labels: bug
