### ISSUE TITLE
Can't compile crow 

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#173] opened 2021-07-26 12:01 UTC
all i get is this `includes/crow_all.h:39:25: error: declaration of 'constexpr' variable 'crow::VERSION' is not a definition
   39 |   extern constexpr char VERSION[];`

this is my folder structure :

`
main.cpp
includes/
    crow_all.h
    boost/
`

i am compiling with `g++ -std=c++17 -o main.exe main.cpp -lpthread -Iincludes/`
i've tried on a linux vm, on an actual raspberrypi zero W and now on windows all of them give that error back

**Comment by The-EDev** [comment] 2021-07-26 12:05
possible duplicate of #150

did you add `#define CROW_MAIN` to the top of your `main.cpp` (above the `#include "crow_all.h"`)?

**Comment by The-EDev** [comment] 2021-07-26 12:35
please let me know if the above comment fixes your issue

**Comment by Iuliean** [comment] 2021-07-26 12:41
@The-EDev  yes. i got some errors after that but they were some missing windows libs that i had to add to the compiller. damn i feel kinda stupid i remember trying that also and it didn't work mb and thank you :)

**Comment by The-EDev** [comment] 2021-07-26 12:45
No problem, and no need to feel stupid, a year ago I had no idea what crow was even. Good luck with your work!

**Closed by The-EDev** 2021-07-26 12:45 UTC
Labels: duplicate
