### ISSUE TITLE
undefined reference to `crow::detail::dumb_timer_queue::tick`

### ISSUE THREAD

**Issue by GopherJ** [CrowCpp/crow#151] opened 2021-06-24 08:28 UTC
```
main.cpp:(.text._ZN4crow6detail16dumb_timer_queue7processEv[_ZN4crow6detail16dumb_timer_queue7processEv]+0xb0): undefined reference to `crow::detail::dumb_timer_queue::tick'
/usr/bin/ld: CMakeFiles/rt_positions_server.dir/main.cpp.o: in function `crow::response::set_static_file_info(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN4crow8response20set_static_file_infoENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4crow8response20set_static_file_infoENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1d6): undefined reference to `crow::mime_types[abi:cxx11]'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rt_positions_server.dir/build.make:109: rt_positions_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/rt_positions_server.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

```

**Comment by The-EDev** [comment] 2021-06-24 08:42
Possible duplicate of #150 (the errors are using MSVC, though they are the same as the ones you're having).

Could you please check and let me know if the solution there fixes your problem?

Thanks

**Comment by druc0d3s** [comment] 2021-07-23 11:06
I have the same issues with g++ v9.3.0:
> g++ -o main main.cpp -lpthread -lboost_system
```
/usr/bin/ld: /tmp/ccsrdJhX.o: in function `crow::detail::dumb_timer_queue::process()':
main.cpp:(.text._ZN4crow6detail16dumb_timer_queue7processEv[_ZN4crow6detail16dumb_timer_queue7processEv]+0x87): undefined reference to `crow::detail::dumb_timer_queue::tick'
/usr/bin/ld: /tmp/ccsrdJhX.o: in function `crow::response::set_static_file_info(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN4crow8response20set_static_file_infoENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4crow8response20set_static_file_infoENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1e0): undefined reference to `crow::mime_types[abi:cxx11]'
collect2: error: ld returned 1 exit status
```

**Comment by The-EDev** [comment] 2021-07-23 11:13
@druc0d3s could you please either include the content of your `main.cpp` and let me know if you followed the solution in #150 and are still getting the error

**Comment by druc0d3s** [comment] 2021-07-23 11:17
> @druc0d3s could you please include the content of your `main.cpp` and let me know if you followed the solution in #150 and are still getting the error

You answer my comment before I managed to delete it. Indeed the problem was that my ``main.cpp`` was missing ``#define CROW_MAIN``. 
Sorry for the confusion and thanks for support!

**Comment by The-EDev** [comment] 2021-07-23 11:25
No worries, I'm glad your problem was fixed. I'll be closing this since the original poster did not respond

**Closed by The-EDev** 2021-07-23 11:25 UTC
Labels: duplicate
