### ISSUE TITLE
Sending file to crow backend

### ISSUE THREAD

**Issue by mihdim777** [CrowCpp/Crow#210] opened 2021-08-24 15:09 UTC
Hello!

I am trying to send a file (any extension) to a backend crow server.

I am using this piece of code and somehow files don't have the same SHA hash.
In Visual Studio I have set to C++17 and Character Set to Use Multi-Byte Character Set.
```cpp
CROW_ROUTE(app, "/file").methods("POST"_method) ([](const crow::request& req){
		crow::multipart::message msg(req);
		
		auto filepath = msg.parts[0].body;
		auto file = msg.parts[1].body;

		auto file_handler = std::ofstream(filepath);
		file_handler << file;

		file_handler.close();

		return crow::response(200, "Ok");
		});
```
What am I doing wrong? 

![image](https://user-images.githubusercontent.com/81242256/130641846-2e1e0c3d-26fc-44d3-8832-57c47999ff93.png)

Thank you!

**Comment by The-EDev** [comment] 2021-08-24 15:31
I ran your code on my machine (Linux), everything worked fine..
![image](https://user-images.githubusercontent.com/60552923/130645537-e022f05e-c4f0-4bf9-b7cd-32f89d0b6f21.png)

**Comment by The-EDev** [comment] 2021-08-24 15:56
Do you mind telling me how you got Crow and which version you're using? Thanks.

**Comment by epajarre** [comment] 2021-08-24 18:33
Does the resulting file have the same size?

I sort of suspect Windows binary/non binary file issue.  You could test opening your output file with binary mode flag.

**Comment by The-EDev** [comment] 2021-08-24 20:18
Sorry for the late response, I was spinning up a windows VM to test, there is definitely something weird going on, Crow seems to be duplicating newlines in the written file.. I'll look into it further

**Comment by The-EDev** [comment] 2021-08-25 02:24
@epajarre I don't have much experience with windows, the example shows a text file and @mihdim777 is saying the SHA checksum isn't matching..

**Comment by The-EDev** [comment] 2021-08-25 02:47
Okay I ran VS debugger, it's not Crow's fault, windows uses `CRLF` (carriage return, line feed) for a newline, somehow when you're doing `file_handler << file;` it's duplicating every `CR` character

Notice how every `0d` in this sequence is being repeated, 
`0d` = `CR`
`0a` = `LF`
![image](https://user-images.githubusercontent.com/60552923/130718084-d7dbad09-58bb-40cf-b627-e4a9df409f0e.png)

**Comment by epajarre** [comment] 2021-08-25 05:23
So using something like this:

` auto file_handler = std::ofstream(filepath,std::ofstream::binary);`

should fix the issue.

**Comment by mihdim777** [comment] 2021-08-25 06:29
Hello!

Sorry for late response!

@The-EDev Thank you very much for investigation. Indeed it was from Windows machine with that CRLF.

@epajarre yes, by specifying binary ofstream did the trick and now they have the same SHA and files are reopened perfectly.

I'm using latest version from this repo.

Do you think it is a good idea to implement in crow a function to handle file opening, writing and closing? Should I create a PR?

**Comment by mihdim777** [comment] 2021-08-25 06:46
Hello!

Also I found this after redownloading this the latest version:

Here is exception threw on this code:

`#define CROW_MAIN
#include "crow.h"

int main()
{
    crow::SimpleApp app;

    CROW_ROUTE(app, "/")([](){
        return "Hello world";
    });

    app.port(18080).multithreaded().run();
}`

And here is the exception stack from routing.h


![image](https://user-images.githubusercontent.com/81242256/130740018-ff227bef-ceb7-4a26-911c-8f13d659e4e6.png)

**Comment by mihdim777** [comment] 2021-08-25 07:41
@The-EDev , @epajarre 

By adding check for blueprints, it works.

![image](https://user-images.githubusercontent.com/81242256/130747875-64e2bf20-caf9-496d-9b3e-a1792bcf89a8.png)

**Comment by The-EDev** [comment] 2021-08-25 11:47
> Also I found this after redownloading this the latest version

Thanks for taking note of this problem, it's been fixed in #208 which I just merged

**Comment by The-EDev** [comment] 2021-08-25 11:50
> Do you think it is a good idea to implement in crow a function to handle file opening, writing and closing?

I'm not sure, `std::ofstream` is already simple enough in my opinion, doesn't make much sense to wrap it

**Comment by The-EDev** [comment] 2021-08-25 11:52
Thanks for your help @epajarre, I had completely forgotten about `std::ofstream::binary`.

I'll close this issue since the problem is fixed.

**Closed by The-EDev** 2021-08-25 11:52 UTC
Labels: bug
