### ISSUE TITLE
Including a {{}} in a mustache template isn't ignored when it's commented out

### ISSUE THREAD

**Issue by lazypenguin34** [CrowCpp/Crow#869] opened 2024-08-17 06:31 UTC
This means an HTML mustache template like this:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Web Server!</title>
</head>
    <body>
        <p>Hello {{person}}!</p> <!-- {{}} defines a simple variable in mustache -->
    </body>
</html>
```
Will give an error like this:
`An uncaught exception occurred: crow::mustache error: empty tag is not allowed`

Removing the {{}} from the comment fixes the problem, but it might be nice to be able to put it in a comment sometimes.

**Comment by gittiver** [comment] 2024-08-18 14:24
I just noticed that you referring to an html-comment. 
mustache has no idea about what kind of file is used as template, therefore this is intended behavior not a bug.

will close this issue.

**Closed by gittiver** 2024-08-18 14:24 UTC
