### ISSUE TITLE
build failed about ASIO_ASSERT

### ISSUE THREAD

**Issue by doraemon-hub-art** [CrowCpp/Crow#474] opened 2022-06-20 16:51 UTC
Sorry sir, I'm a rookie again. I just installed the standalone version of ASIO as you said last time and rebuild it according to the website.
https://crowcpp.org/master/getting_started/setup/linux/

Environment：
ubuntu 20.04.1
gcc 9.4.0
asio 1.18.1

Sorry,I haven't used anything about boost before.

I tried many times to search for a lot of related instructions, but it didn't work out.The error is as follows：

--------------------------------------------------------------------------------------------------------------------------------------------
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/buffered_stream_storage.hpp: In member function ‘void asio::detail::buffered_stream_storage::resize(asio::detail::buffered_stream_storage::size_type)’:
/usr/local/include/asio/detail/buffered_stream_storage.hpp:81:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
   81 |     ASIO_ASSERT(length <= capacity());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/buffered_stream_storage.hpp: In member function ‘void asio::detail::buffered_stream_storage::consume(asio::detail::buffered_stream_storage::size_type)’:
/usr/local/include/asio/detail/buffered_stream_storage.hpp:104:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
  104 |     ASIO_ASSERT(begin_offset_ + count <= end_offset_);
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘void asio::detail::posix_event::signal_all(Lock&) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:56:29:   required from here
/usr/local/include/asio/detail/posix_event.hpp:56:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
   56 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘void asio::detail::posix_event::unlock_and_signal_one(Lock&) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:64:40:   required from here
/usr/local/include/asio/detail/posix_event.hpp:66:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
   66 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘bool asio::detail::posix_event::maybe_unlock_and_signal_one(Lock&) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:80:53:   required from here
/usr/local/include/asio/detail/posix_event.hpp:90:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
   90 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘void asio::detail::posix_event::clear(Lock&) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:89:24:   required from here
/usr/local/include/asio/detail/posix_event.hpp:105:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
  105 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘void asio::detail::posix_event::wait(Lock&) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:96:23:   required from here
/usr/local/include/asio/detail/posix_event.hpp:114:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
  114 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,
      |             ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/asio/detail/assert.hpp:23,
                 from /usr/local/include/asio/execution/any_executor.hpp:21,
                 from /usr/local/include/asio/execution.hpp:19,
                 from /usr/local/include/asio/system_executor.hpp:20,
                 from /usr/local/include/asio/associated_executor.hpp:22,
                 from /usr/local/include/asio.hpp:19,
                 from /usr/local/include/crow/socket_adaptors.h:3,
                 from /usr/local/include/crow.h:7,
                 from main.cpp:1:
/usr/local/include/asio/detail/posix_event.hpp: In instantiation of ‘bool asio::detail::posix_event::wait_for_usec(Lock&, long int) [with Lock = asio::detail::conditionally_enabled_mutex::scoped_lock]’:
/usr/local/include/asio/detail/conditionally_enabled_event.hpp:106:45:   required from here
/usr/local/include/asio/detail/posix_event.hpp:127:5: error: ‘__assert_fail’ was not declared in this scope; did you mean ‘crow::__assert_fail’?
  127 |     ASIO_ASSERT(lock.locked());
      |     ^~~~~~~~~~~
In file included from /usr/local/include/crow/http_parser_merged.h:191,
                 from /usr/local/include/crow.h:3,
                 from main.cpp:1:
/usr/include/assert.h:69:13: note: ‘crow::__assert_fail’ declared here
   69 | extern void __assert_fail (const char *__assertion, const char *__file,

**Comment by doraemon-hub-art** [comment] 2022-06-20 17:27
@The-EDev i just copy the example.
#include <crow.h>
//#include "crow_all.h"

int main()
{
    crow::SimpleApp app; //define your crow application

    //define your endpoint at the root directory
    CROW_ROUTE(app, "/")([](){
        return "Hello world";
    });

    //set the port, set the app to run on multiple threads, and run the app
    app.port(18080).multithreaded().run();
}

**Comment by doraemon-hub-art** [comment] 2022-06-20 17:27
@The-EDev  I just copy the example.
```C++
#include <crow.h>
//#include "crow_all.h"

int main()
{
    crow::SimpleApp app; //define your crow application

    //define your endpoint at the root directory
    CROW_ROUTE(app, "/")([](){
        return "Hello world";
    });

    //set the port, set the app to run on multiple threads, and run the app
    app.port(18080).multithreaded().run();
}


```

**Comment by doraemon-hub-art** [comment] 2022-06-20 17:30
@The-EDev Sorry,I haven't reached the access step yet. The above is a compilation error.

**Comment by The-EDev** [comment] 2022-06-20 19:51
There seems to be an assertion that's failing, and it seems to be deep into ASIO...

**Comment by doraemon-hub-art** [comment] 2022-06-21 01:37
Sorry, I just woke up.Well, is there any solution now?

**Comment by doraemon-hub-art** [comment] 2022-06-21 01:38
@The-EDev Well, is there any solution now?

**Comment by doraemon-hub-art** [comment] 2022-06-21 11:26
@MichaelSB  Sorry Sir,What is the Imo? I opened the file and checked it according to what you said. But I still don't know how to solve it.

**Comment by MichaelSB** [comment] 2022-06-21 11:33
@doraemon-hub-art imo = in my opinion :) I do believe this is something, that should be fixed in crow. I don't think you can do anything in your code to work around this issue. I could be wrong though, did not look too deep.

**Comment by doraemon-hub-art** [comment] 2022-06-21 11:39
@MichaelSB HaHaHa,my English is not  well .Still thanks for your reply.

**Comment by MichaelSB** [comment] 2022-06-22 06:27
@doraemon-hub-art  I cannot reproduce this error at all. I kind of understand where it comes from, but it just works for me. How are you compiling your program? cmake, make, bare g++? Which compile-flags and definitions do you use to compile? The path to asio `/usr/local/include` looks like you did not use your distributions asio-package, but installed it from source as well? How was this configured?

**Comment by luca-schlecker** [comment] 2022-06-22 08:06
I've never found including headers inside namespaces to work especially well. `assert.h` is included in `asio/detail/assert.hpp` in the form of `cassert` (which is just forwarded to `assert.h`) so the symbols should be defined...

**Comment by MichaelSB** [comment] 2022-06-22 08:39
@luca-schlecker Yes. But if assert.h is included first via http_parser_merged.h its symbols are already defined in namespace crow (the error mentions `crow::__assert_fail`) and assert.h is not included again in asio because of the include-guard it has. So the symbols are not in the global namespace, where asio expects them to be. I believe moving down `#include "crow/http_parser_merged.h"` or moving up `#include "crow/socket_adaptors.h"` in crow.h could resolve the issue, because this would force assert.h to be included first via asio. But I'd love to be able to reproduce the issue to make sure my thinking is not too much off :D

**Comment by MichaelSB** [comment] 2022-06-22 09:02
I think not including in namespace crow is the right thing to do. Otherwise this will likely break sometime in the future again for someone. I'll prepare a PR.

**Comment by luca-schlecker** [comment] 2022-06-22 11:47
Could you please try out the fix suggested in #479 so we know if that PR fixes anything.
For that, please clone this Crow fork (from MichaelSB who implemented the fix):
[https://github.com/MichaelSB/Crow](https://github.com/MichaelSB/Crow)
Then switch to this branch: `fix_http_parser_includes`
and reinstall it manually like explained in the guide you referenced at the start (I guess you used the manual system-wide installation)
Would be awesome as I currently can't reproduce your issue.

**Comment by The-EDev** [comment] 2022-06-22 11:50
To add to @luca-schlecker's comment, the command to clone that branch would be `git clone https://github.com/MichaelSB/Crow.git -b fix_http_parser_includes crow_fix_includes`

**Comment by doraemon-hub-art** [comment] 2022-06-22 11:56
@luca-schlecker @MichaelSB @The-EDev  Yes sir ,I reinstall the server system and prepare to reinstall related files :)
I think it may be caused by my poor skills.
Thanks for your serious reply.

**Closed** 2022-06-22 14:43 UTC
Labels: bug
