### ISSUE TITLE
`crow::multipart::message` hangs on request

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#320] opened 2022-01-20 11:54 UTC
i am sending this request
 ```
--d7585ab0-0284-4921-8ed3-dc9c8f6dc4cf
Content-Type: text/plain
Content-Disposition: form-data; name=password

5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
--d7585ab0-0284-4921-8ed3-dc9c8f6dc4cf--
```

to it and it just hangs a response is never sent back

my code is the following 
```cpp
void Site::auth(const crow::request& req, crow::response& resp)
{
    CROW_LOG_INFO << "Login Attempt";
    crow::multipart::message msg(req);
    if(msg.parts[0].body == this->password)
    {
        resp.code = 303;
        resp.set_header("location", "/dashboard");
        resp.add_header("set-cookie", Cookie::generateCookie().toString());
        resp.end();
        return;
    }
    else
    {
        resp.code = 401;
        resp.body = "Failed login attempt";
        resp.end();
        return;
    }
}
```
it works just fine with these requests 

```
------WebKitFormBoundaryBBQ4YQVHhK9X3slD
Content-Disposition: form-data; name="password"

5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
------WebKitFormBoundaryBBQ4YQVHhK9X3slD--
```
```
--f30a8d38-420a-44e4-84b9-a2e136cb068e
Content-Disposition: form-data; name="password"
Content-Length: 64

5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
--f30a8d38-420a-44e4-84b9-a2e136cb068e--
```

i tested both `crow::multipart::message` and `msg.parts[0].body` and i concluded that it hangs on the `crow::multipart::message`

**Comment by The-EDev** [comment] 2022-01-21 03:16
I'm sorry for the late response. But your request seems to work when I test it. Can you provide some reproducible example like a curl request?

**Comment by Iuliean** [comment] 2022-01-21 09:32
i am sending the request with the .Net  `HttpClient`
```cs
        public Task<bool> Auth()
        {
            return Task.Run<bool>(async () =>
            {
                MultipartFormDataContent form = new MultipartFormDataContent();

                form.Add(new StringContent(Password), "password");

                HttpResponseMessage response = await client.PostAsync(Url + "/auth", form);

                Console.WriteLine((int)response.StatusCode);
                
                if (((int)response.StatusCode) == 200)
                    return true;
                else
                    return false;
                
            });
        }
``` 
this is not the only version i tried though 

The second request posted comes from a browser webform that looks like this 
```html
 <form action="/auth" method="POST" enctype="multipart/form-data">
                <input id="password-box" type="password" name="password" placeholder="password">
                <input type="submit" id="submit-button" value="Submit" onclick="hashContent()">
</form>
```

And the last one comes from a java app with `OkHttpClient`
```java
    public void auth(){

        String hash = Hashing.sha256().hashString(password, StandardCharsets.UTF_8).toString();
        RequestBody body = new MultipartBody.Builder().addFormDataPart("password",hash).setType(MultipartBody.FORM).build();

        Request request = new Request.Builder().url(url+"auth").post(body).build();

        try{
            client.newCall(request).execute();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
```

**Comment by The-EDev** [comment] 2022-01-22 12:18
I'm sorry figuring this out took so long, I was looking into the request body while the problem was in the request headers.

For whatever reason, Microsoft decided to wrap the boundary parameter with `" "`. I'm not sure if anyone else does that.

To fix this issue (This will be committed to the master branch soon, I'm just writing it so you can fix it quickly enough) you'll need to change the `multipart.h` file as follows:
```diff
--- include/crow/multipart.h
+++ include/crow/multipart.h
@@ -94,9 +94,16 @@ namespace crow
             std::string get_boundary(const std::string& header) const
             {
                 size_t found = header.find("boundary=");
                 if (found)
-                    return header.substr(found + 9);
+                {
+                    std::string to_return (header.substr(found + 9));
+                    if (to_return[0] == '\"')
+                    {
+                        to_return = to_return.substr(1, to_return.length()-2);
+                    }
+                    return to_return;
+                }
                 return std::string();
             }
 
             std::vector<part> parse_body(std::string body)
```

**Comment by The-EDev** [comment] 2022-01-22 12:18
Marking this as a "good first issue" in case anyone wants to make a PR with the fix before Monday.

**Comment by Iuliean** [comment] 2022-01-22 12:42
@The-EDev thank you. i was actually loosing my mind, i couldn't understand what i was doing wrong :)

**Closed** 2022-02-15 14:10 UTC
Labels: bug, good first issue
