### ISSUE TITLE
Example build issue

### ISSUE THREAD

**Issue by orgg92** [CrowCpp/crow#98] opened 2021-01-14 18:56 UTC
I was trying to build the websocket example in using G++ and the build seems to be failing and am not sure exactly what the problem is - I'm new to the language and terrible at debugging so trying to provide as much information as possible for potential bug (or more likely an issue on my environment).

OS - CentOS7 (RH)
gcc/g++ version 8.3.1.20190223
I'm not sure what version of boost I am using but pulled from github just the other day when building
I have Codeblocks to link with -lpthread and -lboost_system on build and also tried to add a search directory as /usr/local/include (just incase there was some link to this directory)

`Line 10580 - Internal compiler error: in write_expression, at cp/mangle.c:3050`

Codeblocks seems to pull open crow_all.h and points me to the following method:

`//Create a route using a rule (**USE CROW_ROUTE instead**)`
`template <uint64_t Tag>`
`auto route(std::string&& rule)`
`  -> typename std::result_of<decltype(&Router::new_rule_tagged<Tag>)(Router, std::string&&)>::type`
`{`
`  return router_.new_rule_tagged<Tag>(std::move(rule));`
`}`

Let me know i you have any questions I have missed or suggestions

**Comment by The-EDev** [comment] 2021-01-22 10:01
I apologize for the late reply, this issue seems very similar to ipkn#345. The problem is a bug in GCC8, I believe GCC9 fixes the issue, although a workaround is described in https://github.com/ipkn/crow/issues/303#issuecomment-437628235.

I'm sorry again for the late response, let me know if the above solutions fix your issue.

**Comment by The-EDev** [comment] 2021-01-22 10:02
I'll close this for now, feel free to reopen if the issue persists.

**Closed by The-EDev** 2021-01-22 10:02 UTC
