### ISSUE TITLE
Crow's versioning

### ISSUE THREAD

**Issue by luca-schlecker** [CrowCpp/crow#159] opened 2021-06-28 19:25 UTC
I have recently started keeping the [vcpkg port](https://github.com/microsoft/vcpkg/tree/master/ports/crow) up to date.
Crow's newest release has a [semver](https://semver.org/) of `v0.3+1` leading to an incompatibility with [vcpkg](https://github.com/microsoft/vcpkg). `v0.3+1` isn't recognized as a valid version. `v0.3.0+1` seems to be valid just as `v0.3.1` is valid too.

I'd suggest moving to three-digit versioning, leaving out the `+1` completely, and jumping to `v0.3.1` which would also leave room for more patches.

What do you think @The-EDev?

**Comment by The-EDev** [comment] 2021-06-28 19:32
The decision to use + instead of another period for patches is to distinguish between crow's versioning and typical 3 digit semver, since the first digit would imply a completely different product (as opposed to API incompatibility) and the minor version changes can break API.

In my opinion it would be best to release `v0.3.0+1` without using the third digit. But I'm absolutely open to discussing this subject further.

**Comment by The-EDev** [comment] 2021-06-28 19:43
oh, I forgot to say Thank you for maintaining the vcpkg port of crow. I've not used windows in years so any help getting crow to work with windows is very much appreciated.

**Comment by luca-schlecker** [comment] 2021-06-28 19:50
You're welcome. I am locked to Windows and therefore need a way of managing C++ dependencies in a sane way. I am also looking to make more extensive use of Crow to test its stability. 😃

**Comment by luca-schlecker** [comment] 2021-06-28 19:50
The third digit of semver resembles a bugfix/patch:
https://semver.org/#summary:
```
Given a version number MAJOR.MINOR.PATCH, increment the:

 - MAJOR version when you make incompatible API changes,
 - MINOR version when you add functionality in a backwards compatible manner, and
 - PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

And thus I'd have concluded an increment in the patch-version and thus giving `v0.3.1` as the next version.

But I'd also be fine with `v0.3.0+1` if you prefer that. I just want to make sure these changes hit the [vcpkg port](https://github.com/microsoft/vcpkg/tree/master/ports/crow).

**Comment by The-EDev** [comment] 2021-06-28 20:00
> The third digit of semver resembles a bugfix/patch:
> https://semver.org/#summary:
> 
> ```
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>  - MAJOR version when you make incompatible API changes,
>  - MINOR version when you add functionality in a backwards compatible manner, and
>  - PATCH version when you make backwards compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
> ```
> 
> And thus I'd have concluded an increment in the patch-version and thus giving `v0.3.1` as the next version.
> 
> But I'd also be fine with `v0.3.0+1` if you prefer that. I just want to make sure these changes hit the [vcpkg port](https://github.com/microsoft/vcpkg/tree/master/ports/crow).

I've looked into semantic versioning and the keep a changelog format quite a bit when thinking of how to version Crow (I believe the discussion with @mrozigor happened on gitter). The idea was to take what they did and improve upon it. so crow's versioning is as follows:


versioning is `Major`.`Minor`+`Patch` Where:
`Major`: Release status, involves revamping large sections of the codebase (or whether the project is ready for production).
`Minor`: any change that is not major, **API breaking changes included**.
`Patch`: we messed a release up and really need to fix an issue or 2.

My reasoning behind thinking `v0.3.0+1` is a better compromise than `v0.3.1` is the fact that `v0.3.0+1` is not as mainstream as `v0.3.1` and as such a developer would be less likely to assume that Crow uses semver (an assumption like that could lead to someone wasting time upgrading the project thinking all is well only to realize the new version is incompatible and waste more time reverting things).

**Comment by luca-schlecker** [comment] 2021-06-28 20:11
Knowing that, relying on vcpkg's `version-string` could also seem acceptable. No sorting is attempted though, but because of the breaking nature of the `minor`-version, this doesn't seem so bad.

**Comment by The-EDev** [comment] 2021-06-28 22:32
Yeah I guess we could use `version-string` and just have a disclaimer saying vcpkg can't compare crow versions

**Comment by The-EDev** [comment] 2021-06-30 13:57
Closing this issue since the PR in vcpkg has been approved.

**Closed by The-EDev** 2021-06-30 13:57 UTC
Labels: task

**Comment by ras0219-msft** [comment] 2021-07-01 14:33
What about using `0.3.1` and vcpkg's `version` scheme? It is explicitly not semver (that's `version-semver`) and has no semantic meaning other than lexicographic ordering.

Using `version-string` is _really_ unfortunately, because it almost completely prevents us from performing version analysis.

**Comment by luca-schlecker** [comment] 2021-07-01 14:53
Also seems like a good solution. The meaning of the version-digits could be described in the crow repository.

**Comment by The-EDev** [comment] 2021-07-01 14:55
@ras0219-msft the problem is how easy it is to mistake `0.3.1` for semver (which is why I suggested `0.3.0+1`).

I don't want crow to have a problem similar to boost where the upgrade from `1.67.0` to `1.68.0` was API breaking (at least when it came to ASIO)

We could use either `0.3.0+1` or `0.3.1`. I prefer the first but am fine with either. And I am planning to include a section in the documentation describing how Crow is versioned.

**Comment by luca-schlecker** [comment] 2021-07-02 19:13
To use `0.3.0+1` I'd have to explicitly specify `version-semver` and not `version` in the manifest file, which could actually be more deceiving than just having `version: 0.3.1`.
Another possibility could be to use `version: 0.3.0.1`. It seems less common and I wouldn't have to specify `version-semver`.

But I leave it up to you to decide, I'll implement whichever version you choose.

**Comment by The-EDev** [comment] 2021-07-02 19:37
In that case it would then be best to just use `0.3.1` and have disclaimers where relevant (vcpkg related pages).
